AllCops:
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Rails:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: false

HasAndBelongsToMany:
  Enabled: false

Metrics/LineLength:
  Max: 120
